### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by viable-hartman** [guewen/odoo-connector-magento-buildout#1]
I get "Permission denied (publickey)." when running bin/buildout for this address: /usr/bin/bzr branch -q bzr+ssh://bazaar.launchpad.net/~openerp/openerp-command/7.0 /opt/odoo-connector-magento-buildout/openerp-command

**Comment by viable-hartman** [comment]
I removed the ssh requirement and the buildout seemed to proceed, however I also got errors with the git config.  I had to set the git config in buildout.cfg to https in order to clone the repos.

**Comment by guewen** [comment]
Hi,

I changed branches to https, can you try again and reopen if you still have the same issue?

Thanks
