### ISSUE TITLE
Error when run bin/buildout  command on mac os

### ISSUE THREAD

**Issue by fevxie** [guewen/odoo-connector-magento-buildout#3]
Couldn't find index page for 'openerp-command' (maybe misspelled?)
Getting distribution for 'openerp-command'.
anybox.recipe.openerp.base: Could not find or install 'openerp-command'. Please provide it with 'develop' or 'gp.vcsdevelop'. You may download it on https://launchpad.net/openerp-command. Original exception zc.buildout.easy_install.MissingDistribution says: Couldn't find a distribution for 'openerp-command'.
anybox.recipe.openerp.base: 'openerp-command' is a direct soft requirement, retrying without it
While:
  Installing openerp.
Error: There is a version conflict.
We already have: MarkupSafe 0.23

**Comment by guewen** [comment]
Did you use `bootstrap.sh` or `bootstrap.py`?

**Comment by fevxie** [comment]
actually I use bootstrap.sh  and I research the builout file recently. Maybe I need use the newest anybox recipt and didn't need openerp-command addons again

**Comment by guewen** [comment]
I updated the configuration for odoo 8.0 (the branch is now named 8.0), can you try again?
`openerp-command` does no longer exist for version 8.0
