### ISSUE TITLE
Installation error with babel

### ISSUE THREAD

**Issue by matthieuchoplin** [guewen/odoo-connector-magento-buildout#4]
Hi,
I was trying to bootstrap the buildout but got the following error when executing bin/buildout:

```
$ bin/buildout 
The constraint, 1.0, is not consistent with the requirement, 'babel>=1.3'.
While:
  Installing.
  Getting section sphinxbuilder_connector.
  Initializing section sphinxbuilder_connector.
  Installing recipe collective.recipe.sphinxbuilder.
Error: Bad constraint 1.0 babel>=1.3
```

I have installed the dependencies with http://pythonhosted.org/anybox.recipe.openerp/first_steps.html#installing-build-dependencies

I am not sure to understand that issue.
Any help please?

**Comment by guewen** [comment]
I updated the version pinning for babel https://github.com/guewen/odoo-connector-magento-buildout/commit/ba1f90f213a27c33bb34c813ba3b4e77a2828d9f
Thanks for reporting.

**Comment by guewen** [comment]
Not yet corrected. It seems there is another error.

**Comment by guewen** [comment]
It builds. Please be sure to use `bootstrap.sh` so it creates a virtualenv.

**Comment by matthieuchoplin** [comment]
Thanks Guewen, I got an other error with Pillow as well.
I did a fix similar to what you did for babel: https://github.com/guewen/odoo-connector-magento-buildout/pull/5.
And then, it builds.

I think you can close this issue as it is related to the babel error that is now fixed.
