### ISSUE TITLE
Conflicting on merging magentoerpconnect_pricing

### ISSUE THREAD

**Issue by thomich** [guewen/odoo-connector-magento-buildout#6]
tried to update my buildout with latest code to test again and give feedback, but no success anymore:

details: http://paste.ubuntu.com/11258834/

**Comment by guewen** [comment]
Thanks for noticing.
I rebased oca/connector-magento#92 on oca/connector-magento#85 so it should work now. Could you retry and confirm me?

**Comment by thomich** [comment]
THANKS.. looks great now.. testing again and post my test results...
